input_type: stream


filename: data/brs_250.txt
separator: "\t"

channels:
    time: sec
    bp: CH40
    rr: CH46

shifted_channel: bp

window:
    width: 10
    overlap: 9
    iterations: 6

server: "localhost"
port: 9999
